table 'Mapping Location'
	lineageTag: a738bd6a-68c6-4247-8d09-29cc91c3ace8

	column 'Existing Location'
		dataType: string
		lineageTag: 31f5e45d-a58e-4440-b18d-e223145fe58d
		summarizeBy: none
		sourceColumn: Existing Location

		annotation SummarizationSetBy = Automatic

	column 'Correct Location'
		dataType: string
		lineageTag: ed5ba902-49e0-4186-9426-cecc3b71fd82
		summarizeBy: none
		sourceColumn: Correct Location

		annotation SummarizationSetBy = Automatic

	partition 'Mapping Location' = m
		mode: import
		queryGroup: 'Child Queries\Mapping'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fY+7DoMwDEV/xWKmEmqHzi0MkYoYClUHyhAppiAlcQXJ0H59wxupj82+PvfaznOPoUIJjKtHa5ALz58UnJTCz72IGw4hatOgD4ztYANJlv2AY0lP0QKVEJMWpB3WSzcbBNv9etDRZ1IlNQKi0HFjM8S4PNQVlxJStxdNl7NoR1tLUet7z85n/Hvi8LINQijJCnd/StZUjrycxvITuWJrBqKvFmD2fLVP/MpZvAE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Existing Location" = _t, #"Correct Location" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Existing Location", type text}, {"Correct Location", type text}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Correct Location", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

