table 'Merged Subnets'
	lineageTag: bbd26e7a-1c8a-41d7-b419-ebe5c519e5af

	column Subnet
		dataType: string
		lineageTag: 16d7aa1d-a6af-495b-b54c-5046e84c3a53
		summarizeBy: none
		sourceColumn: Subnet

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 44411c0c-980b-4615-ba90-743c7e36a12a
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 4836a3ea-d05a-414c-95c2-d90638de848d
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'Subnet (Decimal)'
		dataType: int64
		formatString: 0
		lineageTag: f75f18d2-aa6c-4935-b667-81bde1a9f56c
		summarizeBy: sum
		sourceColumn: Subnet (Decimal)

		annotation SummarizationSetBy = Automatic

	partition 'Merged Subnets' = m
		mode: import
		queryGroup: 'Child Queries\Merged'
		source =
				let
				    Source = Table.Combine({#"Mapping Manual Missing Subnets", #"Diamond IP IPControl Subnets", #"Network Team Global IP Address Allocation"}),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Subnet", "Location", "Source"}),
				    #"Added Index Column" = Table.AddColumn(#"Removed Other Columns", "Index", each if [Source] = "Manual" then 1 else if [Source] = "Diamond IP IPControl" then 2 else if [Source] = "GIPAA" then 3 else null),
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Added Index Column",{{"Subnet", Order.Ascending}, {"Index", Order.Ascending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Subnet"}),
				    #"Removed Index Column" = Table.RemoveColumns(#"Removed Duplicates",{"Index"}),
				    #"Added IP Address (Decimal) Column" = Table.AddColumn(#"Removed Index Column", "Subnet (Decimal)", each ConvertIPToDecimal(Text.BeforeDelimiter([Subnet],"/")), Int64.Type),
				    #"Sorted by Subnet (Decimal)" = Table.Sort(#"Added IP Address (Decimal) Column",{{"Subnet (Decimal)", Order.Ascending}})
				in
				    #"Sorted by Subnet (Decimal)"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

