table 'Merged SQL Instances'
	lineageTag: 202c0a58-e510-4aee-801b-8525125e3026

	column 'Server Name'
		dataType: string
		lineageTag: 7382926c-5112-4680-b57d-7e41071ccf70
		summarizeBy: none
		sourceColumn: Server Name

		annotation SummarizationSetBy = Automatic

	column 'Full Instance Name'
		dataType: string
		lineageTag: e11e591e-486c-4724-aae8-99391321cdac
		summarizeBy: none
		sourceColumn: Full Instance Name

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 9b9bc9c0-ac24-45a4-90f9-74b14c6ee573
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'SQL Version'
		dataType: string
		lineageTag: 68f03693-7722-4c07-86ac-c733dad12c89
		summarizeBy: none
		sourceColumn: SQL Version

		annotation SummarizationSetBy = Automatic

	column 'SQL Edition'
		dataType: string
		lineageTag: bde08ee3-fa27-4498-a220-a1e9dd02c32a
		summarizeBy: none
		sourceColumn: SQL Edition

		annotation SummarizationSetBy = Automatic

	column Application = LOOKUPVALUE('_All Devices'[Application],'_All Devices'[Name],'Merged SQL Instances'[Server Name])
		lineageTag: 25171afa-da4b-4476-b284-fddf3b88045d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Server In Model' =
			
			IF(
			    NOT ISBLANK(
			        LOOKUPVALUE('_All Devices'[Name], '_All Devices'[Name], 'Merged SQL Instances'[Server Name])
			    ),
			    TRUE(),
			    FALSE()
			)
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6bfef0e8-e3d1-47b0-9115-1b21e1479a72
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Merged SQL Instances' = m
		mode: import
		queryGroup: 'Child Queries\Merged'
		source =
				let
				    CombinedTable = Table.Combine({
				        Table.SelectColumns(#"Azure Arc SQL Instances", {"Server Name", "Full Instance Name", "Source"}),
				        Table.SelectColumns(#"Azure SQL Virtual Machines", {"Server Name", "Source"}),
				        Table.SelectColumns(#"ServiceNow MSSQL Instances", {"Server Name", "Full Instance Name", "Source"}),
				        Table.SelectColumns(#"DB Inventory System Instances", {"Server Name", "Full Instance Name", "Source"}),
				        Table.SelectColumns(#"Snow SQL Servers", {"Server Name", "Source"})
				    }),
				    #"Added Conditional Column1" = Table.AddColumn(CombinedTable, "Sort Index", each if [Source] = "Azure Arc" then 1 else if [Source] = "DB Inventory System" then 2 else if [Source] = "ServiceNow" then 3 else if [Source] = "Azure" then 4 else if [Source] = "Snow License Manager" then 5 else null),
				    #"Sorted Rows1" = Table.Buffer(Table.Sort(#"Added Conditional Column1",{{"Full Instance Name", Order.Ascending}, {"Server Name", Order.Ascending}, {"Sort Index", Order.Ascending}})),
				    #"Removed Duplicates2" = Table.Distinct(#"Sorted Rows1", {"Server Name", "Full Instance Name"}),
				    #"Grouped Rows" = Table.Group(#"Removed Duplicates2", {"Server Name"}, {{"Server Name Count", each Table.RowCount(_), Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates2", {"Server Name"}, #"Grouped Rows", {"Server Name"}, "Server Name Count", JoinKind.LeftOuter),
				    #"Expanded Server Name Count" = Table.ExpandTableColumn(#"Merged Queries", "Server Name Count", {"Server Name Count"}, {"Server Name Count"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Expanded Server Name Count", "Filter Out", each if [Server Name Count] > 1 and [Full Instance Name] = null then true else false),
				    #"Filtered Rows" = Table.SelectRows(#"Added Conditional Column", each ([Filter Out] = false)),
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Filtered Rows",{{"Full Instance Name", Order.Ascending}, {"Server Name", Order.Ascending}, {"Sort Index", Order.Ascending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Full Instance Name", "Server Name"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"Server Name Count", "Filter Out", "Sort Index"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns", {"Full Instance Name"}, #"Azure Arc SQL Instances", {"Full Instance Name"}, "Azure Arc SQL Instances", JoinKind.LeftOuter),
				    #"Expanded Azure Arc SQL Instances" = Table.ExpandTableColumn(#"Merged Queries1", "Azure Arc SQL Instances", {"SQL Version", "SQL Edition"}, {"Azure Arc SQL Instances.SQL Version", "Azure Arc SQL Instances.SQL Edition"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Azure Arc SQL Instances", {"Server Name"}, #"Azure SQL Virtual Machines", {"Server Name"}, "Azure SQL Virtual Machines", JoinKind.LeftOuter),
				    #"Expanded Azure SQL Virtual Machines" = Table.ExpandTableColumn(#"Merged Queries2", "Azure SQL Virtual Machines", {"SQL Version", "SQL Edition"}, {"Azure SQL Virtual Machines.SQL Version", "Azure SQL Virtual Machines.SQL Edition"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Azure SQL Virtual Machines", {"Server Name"}, #"Snow SQL Servers", {"Server Name"}, "Snow SQL Servers", JoinKind.LeftOuter),
				    #"Expanded Snow SQL Servers" = Table.ExpandTableColumn(#"Merged Queries3", "Snow SQL Servers", {"SQL Version", "SQL Edition"}, {"Snow SQL Servers.SQL Version", "Snow SQL Servers.SQL Edition"}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Expanded Snow SQL Servers", "Full Instance Name.SQL Version", each Text.AfterDelimiter([Full Instance Name], "SQL"), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Text After Delimiter", {{"Full Instance Name.SQL Version", each Text.Start(_, 4), type text}}),
				    #"Added Conditional Column2" = Table.AddColumn(#"Extracted First Characters", "SQL Version", each if [Azure Arc SQL Instances.SQL Version] <> null then [Azure Arc SQL Instances.SQL Version] else if [Azure SQL Virtual Machines.SQL Version] <> null then [Azure SQL Virtual Machines.SQL Version] else if [Snow SQL Servers.SQL Version] <> null then [Snow SQL Servers.SQL Version] else if [Full Instance Name.SQL Version] <> null then [Full Instance Name.SQL Version] else null),
				    #"Added Conditional Column3" = Table.AddColumn(#"Added Conditional Column2", "SQL Edition", each if [Azure Arc SQL Instances.SQL Edition] <> null then [Azure Arc SQL Instances.SQL Edition] else if [Azure SQL Virtual Machines.SQL Edition] <> null then [Azure SQL Virtual Machines.SQL Edition] else if [Snow SQL Servers.SQL Edition] <> null then [Snow SQL Servers.SQL Edition] else null),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column3",{"Azure Arc SQL Instances.SQL Version", "Azure Arc SQL Instances.SQL Edition", "Azure SQL Virtual Machines.SQL Version", "Azure SQL Virtual Machines.SQL Edition", "Snow SQL Servers.SQL Version", "Snow SQL Servers.SQL Edition", "Full Instance Name.SQL Version"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"Server Name", type text}, {"Full Instance Name", type text}, {"Source", type text}, {"SQL Version", type text}, {"SQL Edition", type text}}),
				    #"Removed Duplicates1" = Table.Distinct(#"Changed Type")
				in
				    #"Removed Duplicates1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

